<?xml version="1.0"?>
<package format="2">
  <name>localization_pkg</name>
  <version>0.0.0</version>
  <description>The localization_pkg package</description>

  <maintainer email="pedrodeniz11@gmail.com">Pedro Deniz</maintainer>
  <license>BSD</license>

  <author email="robotec.gdl@gmail.com">Blenders team</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>rospy</depend>
  <depend>geometry_msgs</depend>
  <depend>humanoid_nav_msgs</depend>
  <depend>std_srvs</depend>

</package>
